version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      ES_JAVA_OPTS: '-Xms512M -Xmx512M'
      discovery.type: 'single-node'
    ulimits:
        nofile:
           soft: 65536
           hard: 65536

networks:
  default:
    external:
      name: net
